services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:db/changelog/changelog-master.yaml
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: management
      MYSQL_USER: admintest
      MYSQL_PASSWORD: admintest
    ports:
      - "3307:3306"