--create TABLE IF NOT EXISTS card(
--id BIGINT NOT NULL AUTO_INCREMENT,
--user_id BIGINT NOT NULL,
--number VARCHAR(20),
--expiration_date DATE,
--status VARCHAR(10),
--balance BIGINT,
--PRIMARY KEY (id),
--FOREIGN KEY user_id REFERENCES user(id)
--);
--
--create TABLE IF NOT EXISTS user(
--id BIGINT NOT NULL AUTO_INCREMENT,
--name VARCHAR(50),
--PRIMARY KEY (id)
--);
